events {}

http {
  server {
    listen 8123;

    location = / {
      limit_except POST { deny all; }
      proxy_http_version 1.1;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Content-Type text/plain;
      proxy_pass http://clickhouse:8123/?readonly=2;
    }
  }
}
